#define MAX_VULKAN_EXTENSIONS 256
#define MAX_VULKAN_DEVICES 16
#define MAX_QUEUE_PROPS 512
#define STORE_FIELD_SIZE 512
#define MAX_QUEUE_NAME_SIZE 256
#define MAX_QUEUE_FAMILIES 128
#define MAX_QUEUE_COUNT 128

