#ifndef EXPORTED_VULKAN_FUNCTION 
	#define EXPORTED_VULKAN_FUNCTION(function) 
#endif 

EXPORTED_VULKAN_FUNCTION(GetInstanceProcAddr)

#undef EXPORTED_VULKAN_FUNCTION
// 
#ifndef GLOBAL_LEVEL_VULKAN_FUNCTION 
	#define GLOBAL_LEVEL_VULKAN_FUNCTION(function) 
#endif

GLOBAL_LEVEL_VULKAN_FUNCTION(EnumerateInstanceExtensionProperties)
GLOBAL_LEVEL_VULKAN_FUNCTION(EnumerateInstanceLayerProperties)
GLOBAL_LEVEL_VULKAN_FUNCTION(CreateInstance)

#undef GLOBAL_LEVEL_VULKAN_FUNCTION 
// 
#ifndef INSTANCE_LEVEL_VULKAN_FUNCTION 
	#define INSTANCE_LEVEL_VULKAN_FUNCTION(function) 
#endif 

INSTANCE_LEVEL_VULKAN_FUNCTION(vkEnumeratePhysicalDevices)
INSTANCE_LEVEL_VULKAN_FUNCTION(vkEnumerateDeviceExtensionProperties)
INSTANCE_LEVEL_VULKAN_FUNCTION(vkGetPhysicalDeviceFeatures)
INSTANCE_LEVEL_VULKAN_FUNCTION(vkGetPhysicalDeviceProperties)
INSTANCE_LEVEL_VULKAN_FUNCTION(vkGetPhysicalDeviceQueueFamilyProperties)
INSTANCE_LEVEL_VULKAN_FUNCTION(vkGetPhysicalDeviceMemoryProperties)
INSTANCE_LEVEL_VULKAN_FUNCTION(vkGetPhysicalDeviceFormatProperties)
INSTANCE_LEVEL_VULKAN_FUNCTION(vkCreateDevice)
INSTANCE_LEVEL_VULKAN_FUNCTION(vkGetDeviceProcAddr)
INSTANCE_LEVEL_VULKAN_FUNCTION(vkDestroyInstance)

#undef INSTANCE_LEVEL_VULKAN_FUNCTION 
// 
#ifndef INSTANCE_LEVEL_VULKAN_FUNCTION_FROM_EXTENSION 
	#define INSTANCE_LEVEL_VULKAN_FUNCTION_FROM_EXTENSION(function, extension) 
#endif 

INSTANCE_LEVEL_VULKAN_FUNCTION_FROM_EXTENSION(vkGetPhysicalDeviceSurfaceSupportKHR, VK_KHR_SURFACE_EXTENSION_NAME)
INSTANCE_LEVEL_VULKAN_FUNCTION_FROM_EXTENSION(vkGetPhysicalDeviceSurfaceCapabilitiesKHR, VK_KHR_SURFACE_EXTENSION_NAME)
INSTANCE_LEVEL_VULKAN_FUNCTION_FROM_EXTENSION(vkGetPhysicalDeviceSurfaceFormatsKHR, VK_KHR_SURFACE_EXTENSION_NAME)
INSTANCE_LEVEL_VULKAN_FUNCTION_FROM_EXTENSION(vkGetPhysicalDeviceSurfacePresentModesKHR, VK_KHR_SURFACE_EXTENSION_NAME)
INSTANCE_LEVEL_VULKAN_FUNCTION_FROM_EXTENSION(vkDestroySurfaceKHR, VK_KHR_SURFACE_EXTENSION_NAME)

#undef INSTANCE_LEVEL_VULKAN_FUNCTION_FROM_EXTENSION 
// 
#ifndef DEVICE_LEVEL_VULKAN_FUNCTION 
	#define DEVICE_LEVEL_VULKAN_FUNCTION(function) 
#endif 

#undef DEVICE_LEVEL_VULKAN_FUNCTION 
// 
#ifndef DEVICE_LEVEL_VULKAN_FUNCTION_FROM_EXTENSION 
	#define DEVICE_LEVEL_VULKAN_FUNCTION_FROM_EXTENSION(function, extension) 
#endif 

#undef DEVICE_LEVEL_VULKAN_FUNCTION_FROM_EXTENSION

