#ifndef EXPORTED_VULKAN_FUNCTION 
	#define EXPORTED_VULKAN_FUNCTION(function) 
#endif 

EXPORTED_VULKAN_FUNCTION(GetInstanceProcAddr)

#undef EXPORTED_VULKAN_FUNCTION
// 
#ifndef GLOBAL_LEVEL_VULKAN_FUNCTION 
	#define GLOBAL_LEVEL_VULKAN_FUNCTION(function) 
#endif

GLOBAL_LEVEL_VULKAN_FUNCTION(EnumerateInstanceExtensionProperties)
GLOBAL_LEVEL_VULKAN_FUNCTION(EnumerateInstanceLayerProperties)
GLOBAL_LEVEL_VULKAN_FUNCTION(CreateInstance)

#undef GLOBAL_LEVEL_VULKAN_FUNCTION 
// 
#ifndef INSTANCE_LEVEL_VULKAN_FUNCTION 
	#define INSTANCE_LEVEL_VULKAN_FUNCTION(function) 
#endif 

INSTANCE_LEVEL_VULKAN_FUNCTION(EnumeratePhysicalDevices)
INSTANCE_LEVEL_VULKAN_FUNCTION(EnumerateDeviceExtensionProperties)
INSTANCE_LEVEL_VULKAN_FUNCTION(GetPhysicalDeviceFeatures)
INSTANCE_LEVEL_VULKAN_FUNCTION(GetPhysicalDeviceProperties)
INSTANCE_LEVEL_VULKAN_FUNCTION(GetPhysicalDeviceQueueFamilyProperties)
INSTANCE_LEVEL_VULKAN_FUNCTION(GetPhysicalDeviceMemoryProperties)
INSTANCE_LEVEL_VULKAN_FUNCTION(GetPhysicalDeviceFormatProperties)
INSTANCE_LEVEL_VULKAN_FUNCTION(CreateDevice)
INSTANCE_LEVEL_VULKAN_FUNCTION(GetDeviceProcAddr)
INSTANCE_LEVEL_VULKAN_FUNCTION(DestroyInstance)

#undef INSTANCE_LEVEL_VULKAN_FUNCTION 
// 
#ifndef INSTANCE_LEVEL_VULKAN_FUNCTION_FROM_EXTENSION 
	#define INSTANCE_LEVEL_VULKAN_FUNCTION_FROM_EXTENSION(function, extension) 
#endif 

INSTANCE_LEVEL_VULKAN_FUNCTION_FROM_EXTENSION(GetPhysicalDeviceSurfaceSupportKHR, VK_KHR_SURFACE_EXTENSION_NAME)
INSTANCE_LEVEL_VULKAN_FUNCTION_FROM_EXTENSION(GetPhysicalDeviceSurfaceCapabilitiesKHR, VK_KHR_SURFACE_EXTENSION_NAME)
INSTANCE_LEVEL_VULKAN_FUNCTION_FROM_EXTENSION(GetPhysicalDeviceSurfaceFormatsKHR, VK_KHR_SURFACE_EXTENSION_NAME)
INSTANCE_LEVEL_VULKAN_FUNCTION_FROM_EXTENSION(GetPhysicalDeviceSurfacePresentModesKHR, VK_KHR_SURFACE_EXTENSION_NAME)
INSTANCE_LEVEL_VULKAN_FUNCTION_FROM_EXTENSION(DestroySurfaceKHR, VK_KHR_SURFACE_EXTENSION_NAME)

#undef INSTANCE_LEVEL_VULKAN_FUNCTION_FROM_EXTENSION 
// 
#ifndef DEVICE_LEVEL_VULKAN_FUNCTION 
	#define DEVICE_LEVEL_VULKAN_FUNCTION(function) 
#endif 

#undef DEVICE_LEVEL_VULKAN_FUNCTION 
// 
#ifndef DEVICE_LEVEL_VULKAN_FUNCTION_FROM_EXTENSION 
	#define DEVICE_LEVEL_VULKAN_FUNCTION_FROM_EXTENSION(function, extension) 
#endif 

#undef DEVICE_LEVEL_VULKAN_FUNCTION_FROM_EXTENSION

